import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';
const root='C:/Users/toufi/LynkorrContactDevelopment_20260923_135626',out=root+'/A2_V010_REPRO_20260924/lumbar_sensitivity';if(!fs.existsSync(out))fs.mkdirSync(out);
const source=root+'/A2_V010_REPRO_20260924/ModelicaHumanBodyPArtsArticle2.mo',lib=root+'/ModelicaHumanBodyPArts_v0_10_0_RC1.mo',omc='C:/Program Files/OpenModelica1.27.1-64bit/bin/omc.exe',inv=0.115275665089173;
const filter='time|checksPassed|pelvisYaw|lumbarYaw|thoraxYaw|heelShare|broadSupport|stanceAxis|freeDeltaHip.*|groundForce.*|groundMoment.*|energyResidual|minimumROMMargin|body.cutMomentsWorld.*|body.cutForcesWorld.*';
function build(arch){const d=out+'/build_A'+arch;if(!fs.existsSync(d))fs.mkdirSync(d);if(fs.existsSync(d+'/model.exe'))return d;const name='LumbarSweepA'+arch;const spring='{25,20,4,20,10,10,1000,1000,20,1200,2000,2000,kTrans,kTrans,kAx}',damp='{1.5,2,1.5,1,1,1,60,60,2,60,100,100,cTrans,cTrans,cAx}';const mos=`setCommandLineOptions("--maxSizeLinearTearing=300");\nloadModel(Modelica,{"4.1.0"},requireExactVersion=true);\nloadFile("${lib}");\nloadFile("${source}");\nloadString("model ${name} parameter Real kTrans=1000; parameter Real cTrans=50; parameter Real kAx=20; parameter Real cAx=1; extends ModelicaHumanBodyPArtsArticle2.DistributedSupport(rightStance=true,architecture=${arch},ankleAmplitude=15,hipAmplitude=-1,hold=0.6,fall=0.2,impedanceMode=0,freeQ0={0.25,0,0,0.5,-0.03,${inv}},springK=${spring},damperC=${damp},endTime=1.5); end ${name};");\nprint(getErrorString());\nb:=buildModel(${name},startTime=0,stopTime=1.5,numberOfIntervals=750,tolerance=1e-8,method="dassl",outputFormat="csv",fileNamePrefix="model",variableFilter="${filter}");\nprint(getErrorString());`;fs.writeFileSync(d+'/build.mos',mos);const p=spawnSync(omc,['build.mos'],{cwd:d,encoding:'utf8',timeout:900000,maxBuffer:50e6});fs.writeFileSync(d+'/build.log',(p.stdout||'')+'\n'+(p.stderr||''));if(!fs.existsSync(d+'/model.exe'))throw Error('build A'+arch);return d}
const cases=[];for(const k of [100,300,1000,3000])cases.push({factor:'kTrans',value:k,kTrans:k,cTrans:50,kAx:20,cAx:1});for(const c of [10,100])cases.push({factor:'cTrans',value:c,kTrans:1000,cTrans:c,kAx:20,cAx:1});for(const k of [10,40])cases.push({factor:'kAx',value:k,kTrans:1000,cTrans:50,kAx:k,cAx:1});for(const c of [.5,2])cases.push({factor:'cAx',value:c,kTrans:1000,cTrans:50,kAx:20,cAx:c});
const h=s=>(s.match(/"(?:[^"]|"")*"|[^,]+/g)||[]).map(x=>x.replaceAll('"','').trim());function met(p){const l=fs.readFileSync(p,'utf8').trim().split(/\r?\n/),H=h(l.shift()),R=l.map(x=>x.split(',').map(Number)),o={};for(const k of ['pelvisYaw','lumbarYaw','thoraxYaw','heelShare','stanceAxis','freeDeltaHip[1]','groundForce[1]','groundMoment[3]']){const j=H.indexOf(k),a=R.map(r=>r[j]);o[k]={final:a.at(-1),min:Math.min(...a),max:Math.max(...a)}}return o}
const builds={2:build(2),3:build(3)},res=[];
for(const c of cases)for(const arch of [2,3]){const tag=`${c.factor}_${String(c.value).replace('.','p')}_A${arch}`,csv=out+'/'+tag+'.csv';if(!fs.existsSync(csv)){const p=spawnSync(builds[arch]+'/model.exe',['-r='+csv,`-override=kTrans=${c.kTrans},cTrans=${c.cTrans},kAx=${c.kAx},cAx=${c.cAx}`,'-maxStepSize=0.004'],{cwd:builds[arch],encoding:'utf8',timeout:300000,maxBuffer:30e6,env:{...process.env,PATH:path.dirname(omc)+';'+(process.env.PATH||'')}});fs.writeFileSync(out+'/'+tag+'.log',(p.stdout||'')+'\n'+(p.stderr||''));}const status=fs.existsSync(csv)?'PASS':'FAIL';res.push({...c,arch,status,metrics:status==='PASS'?met(csv):{}});fs.writeFileSync(out+'/lumbar_sensitivity_summary.json',JSON.stringify(res,null,2));console.log(tag+' '+status)}
fs.writeFileSync(out+'/lumbar_sensitivity_summary.json',JSON.stringify(res,null,2));