import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';
const root='C:/Users/toufi/LynkorrContactDevelopment_20260923_135626',out=root+'/A2_V010_REPRO_20260924/refinement';if(!fs.existsSync(out))fs.mkdirSync(out);
const source=root+'/A2_V010_REPRO_20260924/ModelicaHumanBodyPArtsArticle2.mo',lib=root+'/ModelicaHumanBodyPArts_v0_10_0_RC1.mo',omc='C:/Program Files/OpenModelica1.27.1-64bit/bin/omc.exe',inv=0.115275665089173;
const filter='time|checksPassed|pelvisYaw|lumbarYaw|thoraxYaw|heelShare|broadSupport|stanceAxis|freeDeltaHip.*|groundForce.*|groundMoment.*|energyResidual|minimumROMMargin|body.cutMomentsWorld.*|body.cutForcesWorld.*';
const settings=[{tag:'base',tol:1e-8,step:.004,int:750},{tag:'fine',tol:1e-9,step:.002,int:1500},{tag:'finer',tol:1e-10,step:.001,int:3000}];
const results=[];
const header=s=>(s.match(/"(?:[^"]|"")*"|[^,]+/g)||[]).map(x=>x.replaceAll('"','').trim());
function read(p){const l=fs.readFileSync(p,'utf8').trim().split(/\r?\n/),h=header(l.shift()),r=l.map(x=>x.split(',').map(Number));return{h,r}}
for(const side of ['R','L'])for(const arch of [1,2,3])for(const se of settings){const id=`ref_${side}_A${arch}_${se.tag}`,d=out+'/'+id;if(!fs.existsSync(d))fs.mkdirSync(d);const csv=d+'/result.csv';if(!fs.existsSync(csv)){const name='RefCase',mods=`rightStance=${side==='R'},architecture=${arch},ankleAmplitude=15,hipAmplitude=-1,hold=0.6,fall=0.2,impedanceMode=0,freeQ0={0.25,0,0,0.5,-0.03,${inv}},endTime=1.5`;const mos=`setCommandLineOptions("--maxSizeLinearTearing=300");\nloadModel(Modelica,{"4.1.0"},requireExactVersion=true);\nloadFile("${lib}");\nloadFile("${source}");\nloadString("model ${name} extends ModelicaHumanBodyPArtsArticle2.DistributedSupport(${mods}); end ${name};");\nprint(getErrorString());\nsimulate(${name},stopTime=1.5,numberOfIntervals=${se.int},tolerance=${se.tol},method="dassl",outputFormat="csv",fileNamePrefix="model",variableFilter="${filter}",simflags="-lv=LOG_STATS -maxStepSize=${se.step}");\nprint(getErrorString());`;fs.writeFileSync(d+'/run.mos',mos);const p=spawnSync(omc,['run.mos'],{cwd:d,encoding:'utf8',timeout:900000,maxBuffer:50e6});fs.writeFileSync(d+'/run.log',(p.stdout||'')+'\n'+(p.stderr||''));if(fs.existsSync(d+'/model_res.csv'))fs.renameSync(d+'/model_res.csv',csv);}
let status='FAIL',met={};if(fs.existsSync(csv)){const x=read(csv),last=x.r.at(-1),ti=x.h.indexOf('time'),ci=x.h.indexOf('checksPassed');status=Math.abs(last[ti]-1.5)<1e-8&&last[ci]>=1?'PASS':'FAIL';for(const k of ['pelvisYaw','lumbarYaw','thoraxYaw','heelShare','stanceAxis','freeDeltaHip[1]','groundForce[1]','groundMoment[3]']){const j=x.h.indexOf(k);if(j>=0){const a=x.r.map(r=>r[j]);met[k]={final:a.at(-1),min:Math.min(...a),max:Math.max(...a)}}}}results.push({id,side,arch,...se,status,metrics:met});fs.writeFileSync(out+'/refinement_results.json',JSON.stringify(results,null,2));console.log(id+' '+status)}
fs.writeFileSync(out+'/refinement_results.json',JSON.stringify(results,null,2));
function interp(x,h,t,k){const j=h.indexOf(k);let lo=0;while(lo+1<x.length&&x[lo+1][0]<t)lo++;if(lo+1>=x.length)return x[lo][j];const a=x[lo],b=x[lo+1],u=(t-a[0])/(b[0]-a[0]);return a[j]+u*(b[j]-a[j])}
const cmp=[];for(const side of ['R','L'])for(const arch of [1,2,3]){const files=settings.map(s=>read(out+`/ref_${side}_A${arch}_${s.tag}/result.csv`));for(let q=0;q<2;q++){const A=files[q],B=files[2],tag=settings[q].tag;for(const k of ['pelvisYaw','lumbarYaw','thoraxYaw','heelShare','stanceAxis','freeDeltaHip[1]','groundForce[1]','groundMoment[3]']){const j=B.h.indexOf(k);let mx=0,scale=k==='heelShare'?.01:(k.includes('Force')?1:(k.includes('Moment')?.1:.001));for(const rb of B.r){const t=rb[0],v=rb[j],va=interp(A.r,A.h,t,k);mx=Math.max(mx,Math.abs(va-v));scale=Math.max(scale,Math.abs(v));}cmp.push({side,arch,coarse:tag,reference:'finer',signal:k,maxAbs:mx,maxNorm:mx/scale});}}}
fs.writeFileSync(out+'/refinement_comparison.json',JSON.stringify(cmp,null,2));console.log(JSON.stringify(cmp.filter(x=>x.coarse==='fine'),null,2));