import fs from 'node:fs'; import path from 'node:path'; import crypto from 'node:crypto'; import {spawnSync} from 'node:child_process';
const root='C:/Users/toufi/LynkorrContactDevelopment_20260923_135626';
const out=root+'/A2_V010_REPRO_20260924/robustness'; fs.mkdirSync(out,{recursive:true});
const lib=root+'/ModelicaHumanBodyPArts_v0_10_0_RC1.mo';
const exp=root+'/A2_V010_REPRO_20260924/ModelicaHumanBodyPArtsArticle2.mo';
const omc='C:/Program Files/OpenModelica1.27.1-64bit/bin/omc.exe';
const inv=0.115275665089173;
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
fs.writeFileSync(out+'/source_hashes.json',JSON.stringify({library_v010_rc1:sha(lib),article2_experiment_package:sha(exp)},null,2));
const filter='time|checksPassed|pelvisYaw|lumbarYaw|thoraxYaw|heelShare|broadSupport|stanceAxis|freeDeltaHip.*|groundForce.*|groundMoment.*|energyResidual|minimumROMMargin|body.cutMomentsWorld.*|body.cutForcesWorld.*';
function head(s){return (s.match(/"(?:[^"]|"")*"|[^,]+/g)||[]).map(x=>x.replaceAll('"','').trim())}
function metrics(csv){const l=fs.readFileSync(csv,'utf8').trim().split(/\r?\n/),h=head(l.shift()),R=l.map(x=>x.split(',').map(Number)),o={rows:R.length,finalTime:R.at(-1)[h.indexOf('time')]}; for(const k of ['checksPassed','pelvisYaw','lumbarYaw','thoraxYaw','heelShare','broadSupport','stanceAxis','freeDeltaHip[1]','groundForce[1]','groundMoment[3]','energyResidual','minimumROMMargin','body.cutMomentsWorld[7,3]']){const j=h.indexOf(k); if(j>=0){const a=R.map(r=>r[j]);o[k]={initial:a[0],final:a.at(-1),min:Math.min(...a),max:Math.max(...a)}}} return o}
function build(arch){const d=out+'/build_A'+arch;fs.mkdirSync(d,{recursive:true});const exe=d+'/model.exe';if(fs.existsSync(exe))return d;const name='A2V010RobustA'+arch;const mods=`rightStance=true,architecture=${arch},ankleAmplitude=15,hipAmplitude=-1,hold=0.6,fall=0.2,impedanceMode=0,freeQ0={0.25,0,0,0.5,-0.03,${inv}},endTime=1.5`;const mos=`setCommandLineOptions("--maxSizeLinearTearing=300");\nloadModel(Modelica,{"4.1.0"},requireExactVersion=true);\nloadFile("${lib}");\nloadFile("${exp}");\nloadString("model ${name} extends ModelicaHumanBodyPArtsArticle2.DistributedSupport(${mods}); end ${name};");\nprint(getErrorString());\nb:=buildModel(${name},startTime=0,stopTime=1.5,numberOfIntervals=750,tolerance=1e-8,method="dassl",outputFormat="csv",fileNamePrefix="model",variableFilter="${filter}");\nprint(getErrorString());`;fs.writeFileSync(d+'/build.mos',mos);const q=spawnSync(omc,['build.mos'],{cwd:d,encoding:'utf8',timeout:900000,maxBuffer:50e6});fs.writeFileSync(d+'/build.log',(q.stdout||'')+'\n'+(q.stderr||''));if(q.status!==0||!fs.existsSync(exe))throw Error('build A'+arch);return d}
const cond=[]; for(const a of [10,15,20])for(const h of [-0.5,-1,-1.5])cond.push({tag:`drive_a${a}_h${String(Math.abs(h)).replace('.','p')}`,ov:`ankleAmplitude=${a},hipAmplitude=${h},friction=0.6,normalStiffness=200000`});
for(const mu of [0.45,0.75])cond.push({tag:`fric_${String(mu).replace('.','p')}`,ov:`ankleAmplitude=15,hipAmplitude=-1,friction=${mu},normalStiffness=200000`});
for(const k of [100000,400000])cond.push({tag:`kn_${k}`,ov:`ankleAmplitude=15,hipAmplitude=-1,friction=0.6,normalStiffness=${k}`});
for(const q of [-0.02,0])cond.push({tag:`posture_a${String(q).replace('-','m').replace('.','p')}`,ov:`ankleAmplitude=15,hipAmplitude=-1,friction=0.6,normalStiffness=200000,freeQ0[5]=${q}`});
const builds={}; for(const a of [1,2,3]){console.log('BUILD A'+a);builds[a]=build(a)}
const res=[]; for(const c of cond)for(const arch of [1,2,3]){const tag=`${c.tag}_A${arch}`,csv=out+'/'+tag+'.csv',log=out+'/'+tag+'.log'; if(!fs.existsSync(csv)){const exe=builds[arch]+'/model.exe';const q=spawnSync(exe,['-r='+csv,'-override='+c.ov,'-lv=LOG_STATS','-maxStepSize=0.004'],{cwd:builds[arch],encoding:'utf8',timeout:300000,maxBuffer:30e6,env:{...process.env,PATH:path.dirname(omc)+';'+(process.env.PATH||'')}});fs.writeFileSync(log,(q.stdout||'')+'\n'+(q.stderr||''));}
let status='FAIL',m={}; try{if(!fs.existsSync(csv))throw Error('no csv');m=metrics(csv);if(m.checksPassed?.final<1||Math.abs(m.finalTime-1.5)>1e-8)throw Error('gate');status='PASS'}catch(e){} res.push({condition:c.tag,arch,status,metrics:m});fs.writeFileSync(out+'/robustness_summary.json',JSON.stringify(res,null,2));console.log(tag+' '+status)}
fs.writeFileSync(out+'/robustness_summary.json',JSON.stringify(res,null,2));console.log('DONE '+res.length);